### ISSUE TITLE
--set doesn't seem to be working

### ISSUE THREAD

**Issue by kris-nova** [kris-nova/kubicorn#381] opened 2017-09-03 01:54 UTC
Trying to tinker with the new `--set` flag

If I do

```bash
kubicorn create knova -p azure --set location=uswest
cat _state/knova/cluster.yaml | grep uswest
```

I get no results

**Comment by xmudrii** [comment] 2017-09-03 06:45
@kris-nova IIRC `--set`‎ is implemented only for `apply` command. Flag exist for `create` as well but logic beside it isn't there.

Should be easy fix. I didn't have time last evening to thinker with it as it was quite late. ‎

**Comment by xmudrii** [comment] 2017-09-03 10:55
Obviously I'm wrong. Will look into this. 
‎

**Comment by xmudrii** [comment] 2017-09-03 16:33
@kris-nova it requires us to use names from Go Struct rather than from config file.
What does this means? In config file `_config.yaml`, field is called `location`, but in appropriate profile Go file, field is called `Location` (capital L).
If you use `kubicorn create knova -p azure --set Location=uswest` it would work.

I don't like this behavior, but I'm pretty much busy today. If nobody takes a look, I'll try to address it tomorrow.

**Comment by xmudrii** [comment] 2017-09-28 20:39
Duplicate of #417

**Closed by xmudrii** 2017-09-28 20:39 UTC
Labels: Bug
