### ISSUE TITLE
Panic while no internet connectivity

### ISSUE THREAD

**Issue by kris-nova** [kris-nova/kubicorn#503] opened 2017-12-08 23:39 UTC
If you try to run a `kubicorn` apply while not connected to the internet you get a nasty panic.

CC @stealthybox

```
knova:kubicorn knova$ kubicorn create knova -p aws
2017-12-08T17:24:55-06:00 [ℹ]  Selected [fs] state store
2017-12-08T17:24:55-06:00 [✿]  The state [./_state/knova/cluster.yaml] has been created. You can edit the file, then run `kubicorn apply knova`
knova:kubicorn knova$ kubicorn apply knova -v 4
2017-12-08T17:25:01-06:00 [ℹ]  Selected [fs] state store
2017-12-08T17:25:01-06:00 [ℹ]  Loaded cluster: knova
2017-12-08T17:25:01-06:00 [ℹ]  Init Cluster
2017-12-08T17:25:01-06:00 [▶]  Running preprocessors
2017-12-08T17:25:01-06:00 [▶]  Running validations
2017-12-08T17:25:01-06:00 [ℹ]  Query existing resources
2017-12-08T17:25:01-06:00 [▶]  keypair.Actual
2017-12-08T17:25:01-06:00 [▶]  keypair.Render
2017-12-08T17:25:01-06:00 [▶]  vpc.Actual
2017-12-08T17:25:01-06:00 [▶]  vpc.Render
2017-12-08T17:25:01-06:00 [▶]  internetgateway.Actual
2017-12-08T17:25:01-06:00 [▶]  internetgateway.Render
2017-12-08T17:25:01-06:00 [▶]  instanceprofile.Actual
2017-12-08T17:25:01-06:00 [▶]  instanceprofile.Render
2017-12-08T17:25:01-06:00 [▶]  securitygroup.Actual
2017-12-08T17:25:01-06:00 [▶]  securitygroup.Render
2017-12-08T17:25:01-06:00 [▶]  subnet.Actual
2017-12-08T17:25:01-06:00 [▶]  subnet.Render
2017-12-08T17:25:01-06:00 [▶]  routetable.Actual
2017-12-08T17:25:01-06:00 [▶]  subnet.Render
2017-12-08T17:25:01-06:00 [▶]  lc.Actual
2017-12-08T17:25:01-06:00 [▶]  lc.Render
2017-12-08T17:25:01-06:00 [▶]  asg.Actual
2017-12-08T17:25:01-06:00 [▶]  asg.Render
2017-12-08T17:25:01-06:00 [▶]  instanceprofile.Actual
2017-12-08T17:25:01-06:00 [▶]  instanceprofile.Render
2017-12-08T17:25:01-06:00 [▶]  securitygroup.Actual
2017-12-08T17:25:01-06:00 [▶]  securitygroup.Render
2017-12-08T17:25:01-06:00 [▶]  subnet.Actual
2017-12-08T17:25:01-06:00 [▶]  subnet.Render
2017-12-08T17:25:01-06:00 [▶]  routetable.Actual
2017-12-08T17:25:01-06:00 [▶]  subnet.Render
2017-12-08T17:25:01-06:00 [▶]  lc.Actual
2017-12-08T17:25:01-06:00 [▶]  lc.Render
2017-12-08T17:25:01-06:00 [▶]  asg.Actual
2017-12-08T17:25:01-06:00 [▶]  asg.Render
2017-12-08T17:25:01-06:00 [▶]  Resetting TimeOut counter.
2017-12-08T17:25:01-06:00 [ℹ]  Resolving expected resources
2017-12-08T17:25:01-06:00 [▶]  keypair.Expected
2017-12-08T17:25:01-06:00 [▶]  keypair.Render
2017-12-08T17:25:01-06:00 [▶]  vpc.Expected
2017-12-08T17:25:01-06:00 [▶]  vpc.Render
2017-12-08T17:25:01-06:00 [▶]  internetgateway.Expected
2017-12-08T17:25:01-06:00 [▶]  internetgateway.Render
2017-12-08T17:25:01-06:00 [▶]  instanceprofile.Expected knova-KubicornMasterInstanceProfile
2017-12-08T17:25:01-06:00 [▶]  instanceprofile.Render
2017-12-08T17:25:01-06:00 [▶]  securitygroup.Expected
2017-12-08T17:25:01-06:00 [▶]  securitygroup.Render
2017-12-08T17:25:01-06:00 [▶]  subnet.Expected
2017-12-08T17:25:01-06:00 [▶]  subnet.Render
2017-12-08T17:25:01-06:00 [▶]  routetable.Expected
2017-12-08T17:25:01-06:00 [▶]  subnet.Render
2017-12-08T17:25:01-06:00 [▶]  asg.Expected
2017-12-08T17:25:01-06:00 [▶]  lc.Render
2017-12-08T17:25:01-06:00 [▶]  asg.Expected
2017-12-08T17:25:01-06:00 [▶]  asg.Render
2017-12-08T17:25:01-06:00 [▶]  instanceprofile.Expected knova-KubicornNodeInstanceProfile
2017-12-08T17:25:01-06:00 [▶]  instanceprofile.Render
2017-12-08T17:25:01-06:00 [▶]  securitygroup.Expected
2017-12-08T17:25:01-06:00 [▶]  securitygroup.Render
2017-12-08T17:25:01-06:00 [▶]  subnet.Expected
2017-12-08T17:25:01-06:00 [▶]  subnet.Render
2017-12-08T17:25:01-06:00 [▶]  routetable.Expected
2017-12-08T17:25:01-06:00 [▶]  subnet.Render
2017-12-08T17:25:01-06:00 [▶]  asg.Expected
2017-12-08T17:25:01-06:00 [▶]  lc.Render
2017-12-08T17:25:01-06:00 [▶]  asg.Expected
2017-12-08T17:25:01-06:00 [▶]  asg.Render
2017-12-08T17:25:01-06:00 [▶]  Resetting TimeOut counter.
2017-12-08T17:25:01-06:00 [ℹ]  Reconciling
2017-12-08T17:25:01-06:00 [▶]  keypair.Actual
2017-12-08T17:25:01-06:00 [▶]  keypair.Render
2017-12-08T17:25:01-06:00 [▶]  keypair.Expected
2017-12-08T17:25:01-06:00 [▶]  keypair.Render
2017-12-08T17:25:01-06:00 [▶]  keypair.Apply
2017-12-08T17:25:01-06:00 [▶]  Actual   : a4cc1af262fba3be49a88a1270739699
2017-12-08T17:25:01-06:00 [▶]  Expected : bb3c0421503f45310bd932dc1324fdf8
2017-12-08T17:25:02-06:00 [✖]  Error during apply of atomic reconciler, attempting clawback: RequestError: send request failed
caused by: Post https://ec2.us-west-2.amazonaws.com/: dial tcp: lookup ec2.us-west-2.amazonaws.com: no such host
2017-12-08T17:25:02-06:00 [!]
2017-12-08T17:25:02-06:00 [!]  Attempting to backtrack and cleanup created resources.
2017-12-08T17:25:02-06:00 [!]
2017-12-08T17:25:02-06:00 [▶]  Resetting TimeOut counter.
2017-12-08T17:25:02-06:00 [▶]  Resetting TimeOut counter.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1086232]

goroutine 1 [running]:
time.(*Timer).Stop(0x0, 0x0)
	/usr/local/Cellar/go/1.9.2/libexec/src/time/sleep.go:75 +0x22
github.com/kris-nova/kubicorn/cutil/signals.(*Handler).Reset(0xc4201fcbc0)
	/go/src/github.com/kris-nova/kubicorn/cutil/signals/signals.go:73 +0x2f
github.com/kris-nova/kubicorn/cloud.teardown()
	/go/src/github.com/kris-nova/kubicorn/cloud/atomic_reconciler.go:202 +0x61
github.com/kris-nova/kubicorn/cloud.(*AtomicReconciler).cleanUp(0xc4201fde80, 0xc420279860, 0x0, 0x0, 0x0)
	/go/src/github.com/kris-nova/kubicorn/cloud/atomic_reconciler.go:92 +0x235
github.com/kris-nova/kubicorn/cloud.(*AtomicReconciler).Reconcile(0xc4201fde80, 0xc4203c1ba0, 0xc4202796c0, 0xc420279860, 0x0, 0x0)
	/go/src/github.com/kris-nova/kubicorn/cloud/atomic_reconciler.go:124 +0x505
github.com/kris-nova/kubicorn/cmd.RunApply(0x25d91e0, 0x1dd8780, 0x1ae4980)
	/go/src/github.com/kris-nova/kubicorn/cmd/apply.go:156 +0x806
github.com/kris-nova/kubicorn/cmd.ApplyCmd.func1(0xc420249200, 0xc420431e00, 0x1, 0x3)
	/go/src/github.com/kris-nova/kubicorn/cmd/apply.go:60 +0x72
github.com/kris-nova/kubicorn/vendor/github.com/spf13/cobra.(*Command).execute(0xc420249200, 0xc420431d70, 0x3, 0x3, 0xc420249200, 0xc420431d70)
	/go/src/github.com/kris-nova/kubicorn/vendor/github.com/spf13/cobra/command.go:653 +0x2a2
github.com/kris-nova/kubicorn/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x25d2d60, 0x1a00da9, 0x1d9baf9, 0x4)
	/go/src/github.com/kris-nova/kubicorn/vendor/github.com/spf13/cobra/command.go:728 +0x2fe
github.com/kris-nova/kubicorn/vendor/github.com/spf13/cobra.(*Command).Execute(0x25d2d60, 0x0, 0x9ea)
	/go/src/github.com/kris-nova/kubicorn/vendor/github.com/spf13/cobra/command.go:687 +0x2b
github.com/kris-nova/kubicorn/cmd.Execute()
	/go/src/github.com/kris-nova/kubicorn/cmd/root.go:85 +0x31
main.main()
	/go/src/github.com/kris-nova/kubicorn/main.go:22 +0x20
knova:kubicorn knova$
```

**Comment by stealthybox** [comment] 2017-12-08 23:39
I'll take a look at this :+1:

**Comment by xmudrii** [comment] 2017-12-08 23:40
‎‎@kris-nova I believe this is related to signals. Check out my PR.

**Comment by xmudrii** [comment] 2017-12-08 23:41
‎Also, check out #501, it contains some important details.

**Comment by xmudrii** [comment] 2017-12-21 11:34
Duplicate of #501, I'll close this one.

**Closed by xmudrii** 2017-12-21 11:34 UTC
Labels: Bug, Help (small)
