### ISSUE TITLE
public ip not getting on digital ocean

### ISSUE THREAD

**Issue by roysG** [kris-nova/kubicorn#532] opened 2018-02-03 16:11 UTC
The scripts works well, but when i do the command to see the public ip, it is not coming.

**Comment by xmudrii** [comment] 2018-02-03 16:13
@roysG Hello there, thanks for reporting the issue.

Because I'm not able to trace it, can you please provide the command you used to obtain Public IP? That would help me a lot.

**Comment by roysG** [comment] 2018-02-03 16:14
ok, one moment.

**Comment by roysG** [comment] 2018-02-03 16:46
I tried to repreduce the problem again, but now i stack on another problem.
The setup soppouse to take so long time??

 kubicorn apply myfirstk8s
2018-02-03T18:39:26+02:00 [ℹ]  Selected [fs] state store
2018-02-03T18:39:26+02:00 [ℹ]  Loaded cluster: myfirstk8s
2018-02-03T18:39:26+02:00 [ℹ]  Init Cluster
2018-02-03T18:39:26+02:00 [ℹ]  Query existing resources
2018-02-03T18:39:28+02:00 [ℹ]  Resolving expected resources
2018-02-03T18:39:28+02:00 [ℹ]  Reconciling
2018-02-03T18:39:29+02:00 [ℹ]  Using existing SSH Key [computer]
2018-02-03T18:39:30+02:00 [ℹ]  Parsing bootstrap script from GitHub [https://raw.githubusercontent.com/kris-nova/kubicorn/master/bootstrap/vpn/openvpnMaster.sh]
2018-02-03T18:39:30+02:00 [ℹ]  Parsing bootstrap script from GitHub [https://raw.githubusercontent.com/kris-nova/kubicorn/master/bootstrap/digitalocean_k8s_ubuntu_16.04_master.sh]
2018-02-03T18:39:32+02:00 [✔]  Created Droplet [81184855]
2018-02-03T18:39:34+02:00 [ℹ]  Setting up VPN on Droplets... this could take a little bit longer...
2018-02-03T18:39:43+02:00 [ℹ]  Setting up VPN on Droplets... this could take a little bit longer...
2018-02-03T18:39:51+02:00 [ℹ]  Setting up VPN on Droplets... this could take a little bit longer...
2018-02-03T18:40:00+02:00 [ℹ]  Setting up VPN on Droplets... this could take a little bit longer...
2018-02-03T18:40:09+02:00 [ℹ]  Setting up VPN on Droplets... this could take a little bit longer...
2018-02-03T18:40:18+02:00 [ℹ]  Setting up VPN on Droplets... this could take a little bit longer...
2018-02-03T18:40:27+02:00 [ℹ]  Setting up VPN on Droplets... this could take a little bit longer...
2018-02-03T18:40:37+02:00 [ℹ]  Setting up VPN on Droplets... this could take a little bit longer...
2018-02-03T18:40:50+02:00 [ℹ]  Setting up VPN on Droplets... this could take a little bit longer...
2018-02-03T18:41:08+02:00 [ℹ]  Setting up VPN on Droplets... this could take a little bit longer...
2018-02-03T18:41:22+02:00 [ℹ]  Setting up VPN on Droplets... this could take a little bit longer...
2018-02-03T18:41:35+02:00 [ℹ]  Setting up VPN on Droplets... this could take a little bit longer...
2018-02-03T18:41:49+02:00 [ℹ]  Setting up VPN on Droplets... this could take a little bit longer...










2018-02-03T18:42:03+02:00 [ℹ]  Setting up VPN on Droplets... this could take a little bit longer...
2018-02-03T18:42:16+02:00 [ℹ]  Setting up VPN on Droplets... this could take a little bit longer...
2018-02-03T18:42:29+02:00 [ℹ]  Setting up VPN on Droplets... this could take a little bit longer...
2018-02-03T18:42:43+02:00 [ℹ]  Setting up VPN on Droplets... this could take a little bit longer...
2018-02-03T18:42:56+02:00 [ℹ]  Setting up VPN on Droplets... this could take a little bit longer...
2018-02-03T18:43:09+02:00 [ℹ]  Setting up VPN on Droplets... this could take a little bit longer...
2018-02-03T18:43:23+02:00 [ℹ]  Setting up VPN on Droplets... this could take a little bit longer...
2018-02-03T18:43:36+02:00 [ℹ]  Setting up VPN on Droplets... this could take a little bit longer...
2018-02-03T18:43:49+02:00 [ℹ]  Setting up VPN on Droplets... this could take a little bit longer...
2018-02-03T18:44:03+02:00 [ℹ]  Setting up VPN on Droplets... this could take a little bit longer...
2018-02-03T18:44:16+02:00 [ℹ]  Setting up VPN on Droplets... this could take a little bit longer...
2018-02-03T18:44:29+02:00 [ℹ]  Setting up VPN on Droplets... this could take a little bit longer...
2018-02-03T18:44:43+02:00 [ℹ]  Setting up VPN on Droplets... this could take a little bit longer...
2018-02-03T18:44:56+02:00 [ℹ]  Setting up VPN on Droplets... this could take a little bit longer...
2018-02-03T18:45:09+02:00 [ℹ]  Setting up VPN on Droplets... this could take a little bit longer...
2018-02-03T18:45:22+02:00 [ℹ]  Setting up VPN on Droplets... this could take a little bit longer...
2018-02-03T18:45:36+02:00 [ℹ]  Setting up VPN on Droplets... this could take a little bit longer...
2018-02-03T18:45:49+02:00 [ℹ]  Setting up VPN on Droplets... this could take a little bit longer...

**Comment by xmudrii** [comment] 2018-02-03 16:50
@roysG Setting up VPN takes several minutes, so it's normal.

Make sure you have the latest version of Kubicorn because we've changed the bootstrap scripts and logic behind it. As of #527, VPN is disabled by default.

Once you get the latest version (you can use `git pull origin master` and `go install`), create the new profile and then apply it. If you have problems again, make sure to post logs so I can track down the issue.

**Comment by roysG** [comment] 2018-02-03 16:53
Is this the last version?

kubicorn version

Kubicorn version:  {"Version":"","GitCommit":"","BuildDate":"2018-02-03 16:52:39.603661 +0000 UTC","GOVersion":"go1.9.3","GOARCH":"amd64","GOOS":"darwin"}

**Comment by xmudrii** [comment] 2018-02-03 16:56
@roysG It doesn't show anything at all because `kubicorn version` is not really working (we still haven't started rolling out the releases). The best way to verify is to pull the latest changes and install kubicorn again (as explained above, `git pull origin master` and `go install`).

**Comment by roysG** [comment] 2018-02-03 17:33
Ok, i upgraded the version and successfully installed :)

Now i want to run nginx and need to deploy it to public ip.

So i am trying to do:

kubectl run my-nginx --image=nginx --replicas=1 --port=80
kubectl expose deployment my-nginx --port=80 --type=LoadBalancer

root@axx-master-0:~# kubectl get svc
NAME         TYPE           CLUSTER-IP    EXTERNAL-IP   PORT(S)        AGE
kubernetes   ClusterIP      10.96.0.1     <none>        443/TCP        7m
my-nginx     LoadBalancer   10.101.18.8   <pending>     80:31664/TCP   13s

And the pending is not ending..

**Comment by xmudrii** [comment] 2018-02-03 17:55
@roysG This is expected behavior. Type `LoadBalancer` is not supported on every cloud provider. Under the hood, it creates a Load Balancer on the cloud provider and then exposes that IP address.

Currently the `LoadBalancer` support is shipped with K8S on providers such as AWS, GCP and Azure.

For DigitalOcean, you'll need to apply CCM, which can be found in [`digitalocean-cloud-controller-manager`](https://github.com/digitalocean/digitalocean-cloud-controller-manager). In the repo, you'll find instructions how you can apply it. There're some examples covering the `LoadBalancer` type as well.

With the rework we've done in #527, we can ship DO-CCM by default, and we have the issue for that (#276).

**Comment by roysG** [comment] 2018-02-03 19:32
Thanks for your comment, i just did not understood if there is any way by your repo to setup the servers with the option to apply the "CCM"

**Comment by xmudrii** [comment] 2018-02-03 19:34
@roysG Not at this point, but I'm planning to take on it quite soon. I'll close the issue now. If you have any additional questions, feel free to reopen it or create a new one.

**Comment by roysG** [comment] 2018-02-03 19:35
Ok, thanks

**Closed by xmudrii** 2018-02-03 19:34 UTC
Labels: Bug, DigitalOcean, NeedsInvestigating
