### ISSUE TITLE
Build a more reliable testing infrastructure? 

### ISSUE THREAD

**Issue by shwsun** [kris-nova/kubicorn#106] opened 2017-07-23 17:34 UTC
It seems that the travis CI is just a make test, I don't think it will be good enough if more PR will be coming this way. Thus, to build a reliable testing infrastructure seem to be on the critical path. Thoughts?

**Comment by kris-nova** [comment] 2017-07-23 20:40
We have an issue open for building out a testing harness #63 that will handle running a test suite - its been on my mind for several weeks  as to how we want to handle this... would love to hear your thoughts on the topic.

Going to close this since it's effectively a dupe of #63

**Closed by kris-nova** 2017-07-23 20:40 UTC
