### ISSUE TITLE
SSH tests

### ISSUE THREAD

**Issue by kris-nova** [kris-nova/kubicorn#272] opened 2017-08-14 02:16 UTC
Can we create a testing avenue in which we run a container that has an SSH server listening, and we validate a number of SSH avenues using the `kubicorn` ssh and scp code avenues?

Primarily

- Regular private key ssh from a file
- SSH agent with a password
- Regular private key with a password 

Happy/Sad paths please :)

**Comment by MyDigitalLife** [comment] 2017-08-21 20:53
@kris-nova Do you have a plan of how we should be able to do this? Is it possible to start a container in travis so we can test ssh into it? Or will we just need to actually deploy a server to test the functionality?

**Comment by xmudrii** [comment] 2017-08-21 21:25
I think that creating a container with SSH keys in it (we can use not password protected keys for start) should do the job. Deploying a server could be too much, as we can get the same result by using container.

I was trying this already but gave up due to lack of the time. I was trying to customize [this](https://docs.docker.com/engine/examples/running_ssh_service/) to accept SSH keys but I failed. Maybe, it can be helpful to you if @kris-nova agrees on Docker solution.

**Comment by MyDigitalLife** [comment] 2017-09-03 11:40
This is fixed when #360 is merged. There is however a problem that another test not related to the SSH is now failing for no good reason. Check this [here](https://travis-ci.org/kris-nova/kubicorn/jobs/271364670#L925). I am not able to reproduce this problem locally so can't really fix it. Can somebody else have a look at this?

**Comment by MyDigitalLife** [comment] 2017-09-06 14:05
@kris-nova Can you have a look at #360?

**Closed** 2017-09-07 20:25 UTC
Labels: Help (medium), Improve, Testing
