### ISSUE TITLE
Something is echoing a pointer in `kubicorn create`

### ISSUE THREAD

**Issue by kris-nova** [kris-nova/kubicorn#380] opened 2017-09-03 01:53 UTC
On master if you run a `kubicorn create` you get some bogus output..

```[kris@kris kubicorn]$ kubicorn create knova -p azure
(0x179c3a0,0xc42031d7d0)
2017-09-02T19:52:02-06:00 [✔]  Selected [fs] state store
2017-09-02T19:52:02-06:00 [✿]  The state [./_state/knova/cluster.yaml] has been created. You can edit the file, then run `kubicorn apply knova`
[kris@kris kubicorn]$ 
```

**Comment by MyDigitalLife** [comment] 2017-09-07 17:54
Haven't been able to reproduce this. Might be a platform specified thing or where you in a other branch then master?

**Comment by xmudrii** [comment] 2017-09-07 18:00
Neither me, I tried with multiple profiles but nothing echoes pointer. @kris-nova do you have whole command?

**Comment by xmudrii** [comment] 2017-09-25 18:59
@kris-nova let's close this as we can't reproduce the issue anymore. if you still have it, please re-open the ticket :)

**Closed by xmudrii** 2017-09-25 18:59 UTC
Labels: Bug

**Comment by kris-nova** [comment] 2017-09-25 19:15
Thanks!!
